version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs
  consumer:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs
  socket:
    build:
      context: ./
    command: ['node', 'index.js']
    ports:
      - "3010:3010"
    depends_on:
      - rabbitmq
    expose:
      - '3010'
    networks:
      - rabbitmq_nodejs
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongodb
    build: .
    command: ['node', 'server.js']
    env_file: ./.env
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    ports:
      - 6868:8080
    stdin_open: true
    tty: true
networks:
  rabbitmq_nodejs:
    driver: bridge
volumes:
  db:
